### ISSUE TITLE
Not specifying content type and accept headers results in any `respond_with` format to trigger

### ISSUE THREAD

**Issue by bbugh** [stimulus-components/stimulus-content-loader#1]
Hi! 👋 Stimulus Components seems like a nice project. This one in particular is useful to borrow one of the nice features from SPAs, rapid page loads with loader-indicated background loads.

But! There's a problem. 🐛 `fetch` is not specifying the content-type and accept headers, so it defaults to `*/*`:

```
=> #<Mime::Type:0x00007fd33950d070 @hash=-2141629074085166111, @string="*/*", @symbol=nil, @synonyms=[]>
```

This means that when using `respond_with`, Rails will return whatever the first format is, regardless of its compatibility:

```ruby
respond_with do |format|
  format.html { this_will_be_called }
  format.js { not_this }
  format.json { not_this }
end
```

Or reordered:

```ruby
respond_with do |format|
  format.json { this_will_be_called }
  format.html { not_this }
  format.js { not_this }
end
```

I think at the very least `fetch` should request with `text/html`:

```js
    fetch(this.data.get('url'), {
      headers:  {
        "Content-Type": "text/html",
        "Accept": "text/html"
      },
    })
      .then(response => response.text())
      .then(html => {
        this.element.innerHTML = html
      })
```

So we can check for `format.html` in `respond_to`.

**Comment by guillaumebriday** [comment]
Hey @bbugh,

Thanks for the issue. You're right, by default, Rails will pick up the first format available if the mime type is not specified.

But, I don't think we should force it in the headers because you can specify it in the url path, for instance:

This will pick up the first format available:
```ruby
<div
  data-controller="content-loader"
  data-content-loader-url="<%= comments_path %>"
></div>
```

For html:
```ruby
<div
  data-controller="content-loader"
  data-content-loader-url="<%= comments_path(format: :html) %>"
></div>
```


For js:
```ruby
<div
  data-controller="content-loader"
  data-content-loader-url="<%= comments_path(format: :js) %>"
></div>
```

And so on

Maybe we should add this in the readme?
